apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/db/secrets
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: secret-volume
        secret:
          secretName: db-secret