apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

secretGenerator:
  - name: db-secret
    literals:
      - username=my-username
      - password=my-password

configMapGenerator:
  - name: myapp-config
    literals:
      - variable=abc
      - number=10