apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: dbpass
    files:
      - dbpass.txt

patches:
  - path: config-map-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: myapp
    path: deployment-patch.yaml