apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

helmCharts:
  - name: hello-world
    repo: https://helm.github.io/examples
    version: 0.1.0
    valuesFile: myValues.yaml

patches:
  - path: service-patch.yaml