apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enterprise

resources:
  - ../../base

secretGenerator:
  - name: dbpass
    files:
      - dbpass.txt
  - name: ldappass
    files:
      - ldappass.txt

patches:
  - path: config-map-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: myapp
    path: deployment-patch.yaml