apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: recaptcha
    files:
      - site_key.txt
      - secret_key.txt

patches:
  - path: config-map-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: myapp
    path: deployment-patch.yaml